import { Poppins } from 'next/font/google'
import '../globals.css'

import { Components } from '@/components'

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
        />
      </head>
      <body className={poppins.className}>
        <Components.Navbar />
        <main className="h-screen bg-black pt-24">{children}</main>
      </body>
    </html>
  )
}
